name: Build and deploy Node.js app to Azure Web App - bookfirst

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # 1. Build the frontend
      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build
          cd ..

      # 2. Copy dist to backend
      - name: Copy dist to backend
        run: |
          rm -rf backend/frontend_dist
          cp -r frontend/dist backend/frontend_dist

      # 3. Install backend dependencies
      - name: Install backend
        run: |
          cd backend
          npm install
          cd ..

      # 4. Zip up only the backend folder (now includes frontend_dist)
      - name: Zip artifact for deployment
        run: |
          zip -r release.zip backend

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          # Make sure this matches your Azure Web App name
          app-name: 'bookfirst'
          
          # The secret containing your publish profile XML
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISH_PROFILE }}
          
          # The folder/package to deploy
          package: 'backend'
