name: Build and deploy Node.js app to Azure Web App - bookfirst

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # 1. Build the frontend
      - name: Build frontend
        run: |
          cd Models/frontend
          npm install
          npm run build
          cd ../..

      # 2. Copy dist to backend
      - name: Copy dist to backend
        run: |
          rm -rf Models/backend/frontend_dist
          cp -r Models/frontend/dist Models/backend/frontend_dist

      # 3. Install backend dependencies
      - name: Install backend
        run: |
          cd Models/backend
          npm install
          cd ../..

      # 4. Zip up only the backend folder (now includes frontend_dist)
      - name: Zip artifact for deployment
        run: zip -r release.zip Models/backend

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_XXXX }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_XXXX }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_XXXX }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bookfirst'
          slot-name: 'Production'
          package: 'Models/backend'
